#b_tree:
#	python b_tree.py

binary_search_tree:
	python binary_tree.py

#bsp_tree:
#	python bsp_tree.py

red_black_tree:
	python red_black_tree.py

#splay_tree:
#	python splay_tree.py

#trie:
#	python trie.py
