SHELL:=/bin/bash

all_products_but_index:
	python all_products_but_index.py

array_duplicates:
	python array_duplicates.py

c_string_reversal:
	gcc c_string_reversal.c -o out
	./out

compute_parity:
	python compute_parity.py

find_duplicates:
	python find_duplicates.py

fizzbuzz:
	python fizzbuzz.py

n-free-string:
	python n_free_string.py

print_powerset:
	python print_powerset.py

spiral_print:
	python spiral_print.py

string_reversal:
	python string_reversal.py

swap_bits:
	python swap_bits.py

test_permutations:
	python test_permutations.py
